package knowledgefacade

import (
	"context"
	"fmt"

	"github.com/ygrip/punakawan/internal/knowledge"
	"github.com/ygrip/punakawan/internal/search"
)

// LegacyLocalKnowledgeProvider is the facade's compatibility provider: a
// KnowledgeProvider/KnowledgeSink over the pre-facade internal/knowledge.Store,
// reusing its existing BM25 ranking (internal/search) rather than
// reimplementing it. It exists only for backward compatibility and
// migration until Mom/Codepedia are real.
type LegacyLocalKnowledgeProvider struct {
	Store *knowledge.Store

	// RankedSearch runs a same-project BM25 query - bind this to
	// App.SearchKnowledge, which also serializes the search index's
	// watermark-gated rebuild against concurrent searches so two callers
	// searching at once don't rebuild it twice. Left nil, Search still
	// works for a cross-project request (below).
	RankedSearch func(search.Request) ([]search.Result, error)

	// Project is this provider instance's own project id. Get and, absent an
	// explicit override in a SearchRequest, Search both operate against it.
	// Empty defers to Store's own scope, mirroring
	// knowledge.Store.GetInProject/SearchInProject's own "" fallback.
	Project string
}

var _ KnowledgeProvider = (*LegacyLocalKnowledgeProvider)(nil)
var _ KnowledgeSink = (*LegacyLocalKnowledgeProvider)(nil)

// Search runs req against this project's ranked BM25 index, or - when req
// names a different ProjectId - falls back to Store.SearchInProject's plain
// substring scan, since the ranked index only ever covers Project's own
// records (mirrors the pre-facade search_knowledge handler exactly).
func (p *LegacyLocalKnowledgeProvider) Search(ctx context.Context, req SearchRequest) ([]ProviderResult, error) {
	if req.ProjectId != "" && req.ProjectId != p.Project {
		records, err := p.Store.SearchInProject(req.ProjectId, req.Query, req.Types, req.Limit)
		if err != nil {
			return nil, fmt.Errorf("knowledgefacade: local: cross-project search in %q: %w", req.ProjectId, err)
		}
		out := make([]ProviderResult, len(records))
		for i, rec := range records {
			rec := rec
			out[i] = ProviderResult{
				Source: SourceLocal,
				Ref:    rec.Id,
				Title:  rec.Title,
				Record: &rec,
				Match:  ProviderResultMatch{Kind: "cross_project_scan"},
				Explanation: []string{
					fmt.Sprintf("Cross-project substring scan of %q (no ranked index spans projects)", req.ProjectId),
				},
			}
		}
		return out, nil
	}

	if p.RankedSearch == nil {
		return nil, fmt.Errorf("knowledgefacade: local: no ranked search configured")
	}
	results, err := p.RankedSearch(search.Request{
		Query:          req.Query,
		Scope:          search.Scope{Project: req.Project, Repository: req.Repository, Module: req.Module, Path: req.Path},
		Types:          req.Types,
		Tags:           req.Tags,
		IncludeRelated: req.IncludeRelated,
		Limit:          req.Limit,
	})
	if err != nil {
		return nil, err
	}
	out := make([]ProviderResult, len(results))
	for i, r := range results {
		rec := r.Record
		out[i] = ProviderResult{
			Source:  SourceLocal,
			Ref:     r.Id,
			Title:   r.Title,
			Summary: r.Summary,
			Score:   r.Score,
			Record:  &rec,
			Match: ProviderResultMatch{
				Kind:   string(r.Match.Kind),
				Fields: r.Match.Fields,
				Terms:  r.Match.Terms,
			},
			Explanation: r.Explanation,
		}
	}
	return out, nil
}

// Get reads one record by id from Project (or Store's own project when
// Project is empty), via Store.GetInProject.
func (p *LegacyLocalKnowledgeProvider) Get(ctx context.Context, ref string) (Record, error) {
	return p.Store.GetInProject(p.Project, ref)
}

// Record persists candidate via Store.Put, returning its own id as the ref -
// Put is an upsert keyed by id, so candidate must already carry one (e.g.
// generated by the caller the way create_knowledge_record does).
func (p *LegacyLocalKnowledgeProvider) Record(ctx context.Context, candidate Record) (string, error) {
	if err := p.Store.Put(candidate); err != nil {
		return "", err
	}
	return candidate.Id, nil
}
