// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

// Manifest describing a TypeScript adapter's identity, transport, capabilities,
// and permissions. See punakawan-go-typescript-detailed-plan.md §5.4.
type AdapterManifest struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Operations corresponds to the JSON schema field "operations".
	Operations AdapterManifestOperations `json:"operations" yaml:"operations" mapstructure:"operations"`

	// Permissions corresponds to the JSON schema field "permissions".
	Permissions AdapterManifestPermissions `json:"permissions" yaml:"permissions" mapstructure:"permissions"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol string `json:"protocol" yaml:"protocol" mapstructure:"protocol"`

	// Provides corresponds to the JSON schema field "provides".
	Provides []string `json:"provides" yaml:"provides" mapstructure:"provides"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime AdapterManifestRuntime `json:"runtime" yaml:"runtime" mapstructure:"runtime"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type AdapterManifestOperations map[string]struct {
	// Approval corresponds to the JSON schema field "approval".
	Approval *AdapterManifestOperationsValueApproval `json:"approval,omitempty,omitzero" yaml:"approval,omitempty" mapstructure:"approval,omitempty"`

	// SideEffect corresponds to the JSON schema field "side_effect".
	SideEffect bool `json:"side_effect" yaml:"side_effect" mapstructure:"side_effect"`
}

type AdapterManifestOperationsValueApproval string

const AdapterManifestOperationsValueApprovalRequired AdapterManifestOperationsValueApproval = "required"

var enumValues_AdapterManifestOperationsValueApproval = []interface{}{
	"required",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifestOperationsValueApproval) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AdapterManifestOperationsValueApproval {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AdapterManifestOperationsValueApproval, v)
	}
	*j = AdapterManifestOperationsValueApproval(v)
	return nil
}

type AdapterManifestPermissions struct {
	// Filesystem corresponds to the JSON schema field "filesystem".
	Filesystem AdapterManifestPermissionsFilesystem `json:"filesystem" yaml:"filesystem" mapstructure:"filesystem"`

	// Network corresponds to the JSON schema field "network".
	Network AdapterManifestPermissionsNetwork `json:"network" yaml:"network" mapstructure:"network"`

	// Secrets corresponds to the JSON schema field "secrets".
	Secrets []string `json:"secrets" yaml:"secrets" mapstructure:"secrets"`
}

type AdapterManifestPermissionsFilesystem struct {
	// Read corresponds to the JSON schema field "read".
	Read []string `json:"read" yaml:"read" mapstructure:"read"`

	// Write corresponds to the JSON schema field "write".
	Write []string `json:"write" yaml:"write" mapstructure:"write"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifestPermissionsFilesystem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["read"]; raw != nil && !ok {
		return fmt.Errorf("field read in AdapterManifestPermissionsFilesystem: required")
	}
	if _, ok := raw["write"]; raw != nil && !ok {
		return fmt.Errorf("field write in AdapterManifestPermissionsFilesystem: required")
	}
	type Plain AdapterManifestPermissionsFilesystem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AdapterManifestPermissionsFilesystem(plain)
	return nil
}

type AdapterManifestPermissionsNetwork struct {
	// Hosts corresponds to the JSON schema field "hosts".
	Hosts []string `json:"hosts" yaml:"hosts" mapstructure:"hosts"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifestPermissionsNetwork) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["hosts"]; raw != nil && !ok {
		return fmt.Errorf("field hosts in AdapterManifestPermissionsNetwork: required")
	}
	type Plain AdapterManifestPermissionsNetwork
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AdapterManifestPermissionsNetwork(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifestPermissions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["filesystem"]; raw != nil && !ok {
		return fmt.Errorf("field filesystem in AdapterManifestPermissions: required")
	}
	if _, ok := raw["network"]; raw != nil && !ok {
		return fmt.Errorf("field network in AdapterManifestPermissions: required")
	}
	if _, ok := raw["secrets"]; raw != nil && !ok {
		return fmt.Errorf("field secrets in AdapterManifestPermissions: required")
	}
	type Plain AdapterManifestPermissions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AdapterManifestPermissions(plain)
	return nil
}

type AdapterManifestRuntime string

const AdapterManifestRuntimeNode AdapterManifestRuntime = "node"

var enumValues_AdapterManifestRuntime = []interface{}{
	"node",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifestRuntime) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AdapterManifestRuntime {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AdapterManifestRuntime, v)
	}
	*j = AdapterManifestRuntime(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdapterManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in AdapterManifest: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in AdapterManifest: required")
	}
	if _, ok := raw["operations"]; raw != nil && !ok {
		return fmt.Errorf("field operations in AdapterManifest: required")
	}
	if _, ok := raw["permissions"]; raw != nil && !ok {
		return fmt.Errorf("field permissions in AdapterManifest: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in AdapterManifest: required")
	}
	if _, ok := raw["provides"]; raw != nil && !ok {
		return fmt.Errorf("field provides in AdapterManifest: required")
	}
	if _, ok := raw["runtime"]; raw != nil && !ok {
		return fmt.Errorf("field runtime in AdapterManifest: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in AdapterManifest: required")
	}
	type Plain AdapterManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9]+(-[a-z0-9]+)*$`, string(plain.Id)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Id", `^[a-z0-9]+(-[a-z0-9]+)*$`)
	}
	if plain.Protocol != "punakawan.adapter/v1" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol", "punakawan.adapter/v1")
	}
	if plain.Provides != nil && len(plain.Provides) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "provides", 1)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$`, string(plain.Version)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Version", `^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$`)
	}
	*j = AdapterManifest(plain)
	return nil
}

// A recorded approval decision for a policy-gated operation. See
// punakawan-go-typescript-detailed-plan.md §16.
type ApprovalRecord struct {
	// ApprovedBy corresponds to the JSON schema field "approved_by".
	ApprovedBy *string `json:"approved_by,omitempty,omitzero" yaml:"approved_by,omitempty" mapstructure:"approved_by,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Operation corresponds to the JSON schema field "operation".
	Operation ApprovalRecordOperation `json:"operation" yaml:"operation" mapstructure:"operation"`

	// PolicyLevel corresponds to the JSON schema field "policy_level".
	PolicyLevel *ApprovalRecordPolicyLevel `json:"policy_level,omitempty,omitzero" yaml:"policy_level,omitempty" mapstructure:"policy_level,omitempty"`

	// Preview corresponds to the JSON schema field "preview".
	Preview *string `json:"preview,omitempty,omitzero" yaml:"preview,omitempty" mapstructure:"preview,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty,omitzero" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// RequestedBy corresponds to the JSON schema field "requested_by".
	RequestedBy ApprovalRecordRequestedBy `json:"requested_by" yaml:"requested_by" mapstructure:"requested_by"`

	// ResolvedAt corresponds to the JSON schema field "resolved_at".
	ResolvedAt *time.Time `json:"resolved_at,omitempty,omitzero" yaml:"resolved_at,omitempty" mapstructure:"resolved_at,omitempty"`

	// RunId corresponds to the JSON schema field "run_id".
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// Status corresponds to the JSON schema field "status".
	Status ApprovalRecordStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Target corresponds to the JSON schema field "target".
	Target *string `json:"target,omitempty,omitzero" yaml:"target,omitempty" mapstructure:"target,omitempty"`
}

type ApprovalRecordOperation string

const ApprovalRecordOperationConfluenceUpdate ApprovalRecordOperation = "confluence-update"
const ApprovalRecordOperationDeploymentAction ApprovalRecordOperation = "deployment-action"
const ApprovalRecordOperationDestructiveFilesystemAction ApprovalRecordOperation = "destructive-filesystem-action"
const ApprovalRecordOperationExistingBrowserSessionAccess ApprovalRecordOperation = "existing-browser-session-access"
const ApprovalRecordOperationExternalWrite ApprovalRecordOperation = "external-write"
const ApprovalRecordOperationGitPush ApprovalRecordOperation = "git-push"
const ApprovalRecordOperationIssueCreation ApprovalRecordOperation = "issue-creation"
const ApprovalRecordOperationIssueTransition ApprovalRecordOperation = "issue-transition"
const ApprovalRecordOperationNetworkHostExpansion ApprovalRecordOperation = "network-host-expansion"
const ApprovalRecordOperationPullRequestCreation ApprovalRecordOperation = "pull-request-creation"
const ApprovalRecordOperationSecretAccess ApprovalRecordOperation = "secret-access"

var enumValues_ApprovalRecordOperation = []interface{}{
	"external-write",
	"git-push",
	"pull-request-creation",
	"issue-creation",
	"issue-transition",
	"confluence-update",
	"existing-browser-session-access",
	"secret-access",
	"network-host-expansion",
	"destructive-filesystem-action",
	"deployment-action",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRecordOperation) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRecordOperation {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRecordOperation, v)
	}
	*j = ApprovalRecordOperation(v)
	return nil
}

type ApprovalRecordPolicyLevel string

const ApprovalRecordPolicyLevelAllow ApprovalRecordPolicyLevel = "allow"
const ApprovalRecordPolicyLevelAllowWithConstraints ApprovalRecordPolicyLevel = "allow-with-constraints"
const ApprovalRecordPolicyLevelDeny ApprovalRecordPolicyLevel = "deny"
const ApprovalRecordPolicyLevelRequireApproval ApprovalRecordPolicyLevel = "require-approval"

var enumValues_ApprovalRecordPolicyLevel = []interface{}{
	"deny",
	"require-approval",
	"allow",
	"allow-with-constraints",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRecordPolicyLevel) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRecordPolicyLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRecordPolicyLevel, v)
	}
	*j = ApprovalRecordPolicyLevel(v)
	return nil
}

type ApprovalRecordRequestedBy string

const ApprovalRecordRequestedByBagong ApprovalRecordRequestedBy = "bagong"
const ApprovalRecordRequestedByGareng ApprovalRecordRequestedBy = "gareng"
const ApprovalRecordRequestedByPetruk ApprovalRecordRequestedBy = "petruk"
const ApprovalRecordRequestedBySemar ApprovalRecordRequestedBy = "semar"

var enumValues_ApprovalRecordRequestedBy = []interface{}{
	"semar",
	"gareng",
	"petruk",
	"bagong",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRecordRequestedBy) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRecordRequestedBy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRecordRequestedBy, v)
	}
	*j = ApprovalRecordRequestedBy(v)
	return nil
}

type ApprovalRecordStatus string

const ApprovalRecordStatusApproved ApprovalRecordStatus = "approved"
const ApprovalRecordStatusDenied ApprovalRecordStatus = "denied"
const ApprovalRecordStatusPending ApprovalRecordStatus = "pending"

var enumValues_ApprovalRecordStatus = []interface{}{
	"pending",
	"approved",
	"denied",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRecordStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRecordStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRecordStatus, v)
	}
	*j = ApprovalRecordStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRecord) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in ApprovalRecord: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ApprovalRecord: required")
	}
	if _, ok := raw["operation"]; raw != nil && !ok {
		return fmt.Errorf("field operation in ApprovalRecord: required")
	}
	if _, ok := raw["requested_by"]; raw != nil && !ok {
		return fmt.Errorf("field requested_by in ApprovalRecord: required")
	}
	if _, ok := raw["run_id"]; raw != nil && !ok {
		return fmt.Errorf("field run_id in ApprovalRecord: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in ApprovalRecord: required")
	}
	type Plain ApprovalRecord
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ApprovalRecord(plain)
	return nil
}

// A normalized, semantic browser flow recorded by the human-guided recorder. See
// punakawan-go-typescript-detailed-plan.md §12.9.
type BrowserFlow struct {
	// Expected corresponds to the JSON schema field "expected".
	Expected []BrowserFlowExpectedElem `json:"expected,omitempty,omitzero" yaml:"expected,omitempty" mapstructure:"expected,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Preconditions corresponds to the JSON schema field "preconditions".
	Preconditions []string `json:"preconditions,omitempty,omitzero" yaml:"preconditions,omitempty" mapstructure:"preconditions,omitempty"`

	// Purpose corresponds to the JSON schema field "purpose".
	Purpose BrowserFlowPurpose `json:"purpose" yaml:"purpose" mapstructure:"purpose"`

	// Relations corresponds to the JSON schema field "relations".
	Relations []BrowserFlowRelationsElem `json:"relations,omitempty,omitzero" yaml:"relations,omitempty" mapstructure:"relations,omitempty"`

	// Steps corresponds to the JSON schema field "steps".
	Steps []BrowserFlowStepsElem `json:"steps" yaml:"steps" mapstructure:"steps"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type BrowserFlowExpectedElem struct {
	// Type corresponds to the JSON schema field "type".
	Type BrowserFlowExpectedElemType `json:"type" yaml:"type" mapstructure:"type"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type BrowserFlowExpectedElemType string

const BrowserFlowExpectedElemTypeElementVisible BrowserFlowExpectedElemType = "element_visible"
const BrowserFlowExpectedElemTypeTextVisible BrowserFlowExpectedElemType = "text_visible"
const BrowserFlowExpectedElemTypeUrlMatches BrowserFlowExpectedElemType = "url_matches"

var enumValues_BrowserFlowExpectedElemType = []interface{}{
	"text_visible",
	"url_matches",
	"element_visible",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowExpectedElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BrowserFlowExpectedElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BrowserFlowExpectedElemType, v)
	}
	*j = BrowserFlowExpectedElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowExpectedElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in BrowserFlowExpectedElem: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in BrowserFlowExpectedElem: required")
	}
	type Plain BrowserFlowExpectedElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BrowserFlowExpectedElem(plain)
	return nil
}

type BrowserFlowPurpose struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor" yaml:"actor" mapstructure:"actor"`

	// Goal corresponds to the JSON schema field "goal".
	Goal string `json:"goal" yaml:"goal" mapstructure:"goal"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowPurpose) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actor"]; raw != nil && !ok {
		return fmt.Errorf("field actor in BrowserFlowPurpose: required")
	}
	if _, ok := raw["goal"]; raw != nil && !ok {
		return fmt.Errorf("field goal in BrowserFlowPurpose: required")
	}
	type Plain BrowserFlowPurpose
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BrowserFlowPurpose(plain)
	return nil
}

type BrowserFlowRelationsElem struct {
	// Target corresponds to the JSON schema field "target".
	Target string `json:"target" yaml:"target" mapstructure:"target"`

	// Type corresponds to the JSON schema field "type".
	Type BrowserFlowRelationsElemType `json:"type" yaml:"type" mapstructure:"type"`
}

type BrowserFlowRelationsElemType string

const BrowserFlowRelationsElemTypeAutomatedBy BrowserFlowRelationsElemType = "automated-by"
const BrowserFlowRelationsElemTypeValidates BrowserFlowRelationsElemType = "validates"

var enumValues_BrowserFlowRelationsElemType = []interface{}{
	"validates",
	"automated-by",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowRelationsElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BrowserFlowRelationsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BrowserFlowRelationsElemType, v)
	}
	*j = BrowserFlowRelationsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowRelationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["target"]; raw != nil && !ok {
		return fmt.Errorf("field target in BrowserFlowRelationsElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in BrowserFlowRelationsElem: required")
	}
	type Plain BrowserFlowRelationsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BrowserFlowRelationsElem(plain)
	return nil
}

type BrowserFlowStepsElem struct {
	// Action corresponds to the JSON schema field "action".
	Action BrowserFlowStepsElemAction `json:"action" yaml:"action" mapstructure:"action"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Route corresponds to the JSON schema field "route".
	Route *string `json:"route,omitempty,omitzero" yaml:"route,omitempty" mapstructure:"route,omitempty"`

	// Target corresponds to the JSON schema field "target".
	Target *BrowserFlowStepsElemTarget `json:"target,omitempty,omitzero" yaml:"target,omitempty" mapstructure:"target,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

type BrowserFlowStepsElemAction string

const BrowserFlowStepsElemActionCheck BrowserFlowStepsElemAction = "check"
const BrowserFlowStepsElemActionClick BrowserFlowStepsElemAction = "click"
const BrowserFlowStepsElemActionFill BrowserFlowStepsElemAction = "fill"
const BrowserFlowStepsElemActionKeyboard BrowserFlowStepsElemAction = "keyboard"
const BrowserFlowStepsElemActionNavigate BrowserFlowStepsElemAction = "navigate"
const BrowserFlowStepsElemActionSelect BrowserFlowStepsElemAction = "select"
const BrowserFlowStepsElemActionSubmit BrowserFlowStepsElemAction = "submit"
const BrowserFlowStepsElemActionUncheck BrowserFlowStepsElemAction = "uncheck"

var enumValues_BrowserFlowStepsElemAction = []interface{}{
	"navigate",
	"click",
	"fill",
	"select",
	"check",
	"uncheck",
	"submit",
	"keyboard",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowStepsElemAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BrowserFlowStepsElemAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BrowserFlowStepsElemAction, v)
	}
	*j = BrowserFlowStepsElemAction(v)
	return nil
}

type BrowserFlowStepsElemTarget struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// NamePattern corresponds to the JSON schema field "name_pattern".
	NamePattern *string `json:"name_pattern,omitempty,omitzero" yaml:"name_pattern,omitempty" mapstructure:"name_pattern,omitempty"`

	// Placeholder corresponds to the JSON schema field "placeholder".
	Placeholder *string `json:"placeholder,omitempty,omitzero" yaml:"placeholder,omitempty" mapstructure:"placeholder,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role *string `json:"role,omitempty,omitzero" yaml:"role,omitempty" mapstructure:"role,omitempty"`

	// Text corresponds to the JSON schema field "text".
	Text *string `json:"text,omitempty,omitzero" yaml:"text,omitempty" mapstructure:"text,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlowStepsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in BrowserFlowStepsElem: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in BrowserFlowStepsElem: required")
	}
	type Plain BrowserFlowStepsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BrowserFlowStepsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserFlow) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in BrowserFlow: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in BrowserFlow: required")
	}
	if _, ok := raw["purpose"]; raw != nil && !ok {
		return fmt.Errorf("field purpose in BrowserFlow: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in BrowserFlow: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in BrowserFlow: required")
	}
	type Plain BrowserFlow
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Steps != nil && len(plain.Steps) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 1)
	}
	if 1 > plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = BrowserFlow(plain)
	return nil
}

// An immutable, hashable, bounded context handed to one Gareng/Petruk/Bagong
// invocation. See punakawan-architecture-enhancement-plan.md §6 and AEP-M1
// (punokawan-0m9). Digest is computed over
// role/objective/requirements/acceptance_criteria/constraints/relevant_knowledge/evidence/allowed_tools/forbidden_actions
// per §6.3 and must be recomputed (not mutated in place) if any of those fields
// change.
type ContextCapsule struct {
	// AcceptanceCriteria corresponds to the JSON schema field "acceptance_criteria".
	AcceptanceCriteria []string `json:"acceptance_criteria,omitempty,omitzero" yaml:"acceptance_criteria,omitempty" mapstructure:"acceptance_criteria,omitempty"`

	// AllowedTools corresponds to the JSON schema field "allowed_tools".
	AllowedTools []string `json:"allowed_tools" yaml:"allowed_tools" mapstructure:"allowed_tools"`

	// Assumptions corresponds to the JSON schema field "assumptions".
	Assumptions []string `json:"assumptions,omitempty,omitzero" yaml:"assumptions,omitempty" mapstructure:"assumptions,omitempty"`

	// Constraints corresponds to the JSON schema field "constraints".
	Constraints []string `json:"constraints,omitempty,omitzero" yaml:"constraints,omitempty" mapstructure:"constraints,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest" yaml:"digest" mapstructure:"digest"`

	// Evidence corresponds to the JSON schema field "evidence".
	Evidence []ContextCapsuleEvidenceElem `json:"evidence,omitempty,omitzero" yaml:"evidence,omitempty" mapstructure:"evidence,omitempty"`

	// ExpectedOutput corresponds to the JSON schema field "expected_output".
	ExpectedOutput *string `json:"expected_output,omitempty,omitzero" yaml:"expected_output,omitempty" mapstructure:"expected_output,omitempty"`

	// ForbiddenActions corresponds to the JSON schema field "forbidden_actions".
	ForbiddenActions []string `json:"forbidden_actions" yaml:"forbidden_actions" mapstructure:"forbidden_actions"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Objective corresponds to the JSON schema field "objective".
	Objective string `json:"objective" yaml:"objective" mapstructure:"objective"`

	// RelevantKnowledge corresponds to the JSON schema field "relevant_knowledge".
	RelevantKnowledge []ContextCapsuleRelevantKnowledgeElem `json:"relevant_knowledge,omitempty,omitzero" yaml:"relevant_knowledge,omitempty" mapstructure:"relevant_knowledge,omitempty"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements []ContextCapsuleRequirementsElem `json:"requirements,omitempty,omitzero" yaml:"requirements,omitempty" mapstructure:"requirements,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role ContextCapsuleRole `json:"role" yaml:"role" mapstructure:"role"`

	// TaskId corresponds to the JSON schema field "task_id".
	TaskId string `json:"task_id" yaml:"task_id" mapstructure:"task_id"`

	// TokenBudget corresponds to the JSON schema field "token_budget".
	TokenBudget *int `json:"token_budget,omitempty,omitzero" yaml:"token_budget,omitempty" mapstructure:"token_budget,omitempty"`

	// UnresolvedQuestions corresponds to the JSON schema field
	// "unresolved_questions".
	UnresolvedQuestions []string `json:"unresolved_questions,omitempty,omitzero" yaml:"unresolved_questions,omitempty" mapstructure:"unresolved_questions,omitempty"`
}

type ContextCapsuleEvidenceElem struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextCapsuleEvidenceElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ContextCapsuleEvidenceElem: required")
	}
	type Plain ContextCapsuleEvidenceElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ContextCapsuleEvidenceElem(plain)
	return nil
}

type ContextCapsuleRelevantKnowledgeElem struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextCapsuleRelevantKnowledgeElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ContextCapsuleRelevantKnowledgeElem: required")
	}
	type Plain ContextCapsuleRelevantKnowledgeElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ContextCapsuleRelevantKnowledgeElem(plain)
	return nil
}

type ContextCapsuleRequirementsElem struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextCapsuleRequirementsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ContextCapsuleRequirementsElem: required")
	}
	type Plain ContextCapsuleRequirementsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ContextCapsuleRequirementsElem(plain)
	return nil
}

type ContextCapsuleRole string

const ContextCapsuleRoleBagong ContextCapsuleRole = "bagong"
const ContextCapsuleRoleGareng ContextCapsuleRole = "gareng"
const ContextCapsuleRolePetruk ContextCapsuleRole = "petruk"

var enumValues_ContextCapsuleRole = []interface{}{
	"gareng",
	"petruk",
	"bagong",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextCapsuleRole) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ContextCapsuleRole {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ContextCapsuleRole, v)
	}
	*j = ContextCapsuleRole(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextCapsule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["allowed_tools"]; raw != nil && !ok {
		return fmt.Errorf("field allowed_tools in ContextCapsule: required")
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in ContextCapsule: required")
	}
	if _, ok := raw["digest"]; raw != nil && !ok {
		return fmt.Errorf("field digest in ContextCapsule: required")
	}
	if _, ok := raw["forbidden_actions"]; raw != nil && !ok {
		return fmt.Errorf("field forbidden_actions in ContextCapsule: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ContextCapsule: required")
	}
	if _, ok := raw["objective"]; raw != nil && !ok {
		return fmt.Errorf("field objective in ContextCapsule: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in ContextCapsule: required")
	}
	if _, ok := raw["task_id"]; raw != nil && !ok {
		return fmt.Errorf("field task_id in ContextCapsule: required")
	}
	type Plain ContextCapsule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^sha256:[0-9a-f]{64}$`, string(plain.Digest)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Digest", `^sha256:[0-9a-f]{64}$`)
	}
	if plain.TokenBudget != nil && 1 > *plain.TokenBudget {
		return fmt.Errorf("field %s: must be >= %v", "token_budget", 1)
	}
	*j = ContextCapsule(plain)
	return nil
}

// Structured event record written to the JSONL event journal. See
// punakawan-go-typescript-detailed-plan.md §7.5, §19.1.
type Event struct {
	// Adapter corresponds to the JSON schema field "adapter".
	Adapter *string `json:"adapter,omitempty,omitzero" yaml:"adapter,omitempty" mapstructure:"adapter,omitempty"`

	// ApprovalId corresponds to the JSON schema field "approval_id".
	ApprovalId *string `json:"approval_id,omitempty,omitzero" yaml:"approval_id,omitempty" mapstructure:"approval_id,omitempty"`

	// DurationMs corresponds to the JSON schema field "duration_ms".
	DurationMs *int `json:"duration_ms,omitempty,omitzero" yaml:"duration_ms,omitempty" mapstructure:"duration_ms,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Operation corresponds to the JSON schema field "operation".
	Operation string `json:"operation" yaml:"operation" mapstructure:"operation"`

	// Payload corresponds to the JSON schema field "payload".
	Payload EventPayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository *string `json:"repository,omitempty,omitzero" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Result corresponds to the JSON schema field "result".
	Result EventResult `json:"result" yaml:"result" mapstructure:"result"`

	// Role corresponds to the JSON schema field "role".
	Role *EventRole `json:"role,omitempty,omitzero" yaml:"role,omitempty" mapstructure:"role,omitempty"`

	// RunId corresponds to the JSON schema field "run_id".
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// Task corresponds to the JSON schema field "task".
	Task *string `json:"task,omitempty,omitzero" yaml:"task,omitempty" mapstructure:"task,omitempty"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp time.Time `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`

	// Tool corresponds to the JSON schema field "tool".
	Tool *string `json:"tool,omitempty,omitzero" yaml:"tool,omitempty" mapstructure:"tool,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// Workflow corresponds to the JSON schema field "workflow".
	Workflow *string `json:"workflow,omitempty,omitzero" yaml:"workflow,omitempty" mapstructure:"workflow,omitempty"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace *string `json:"workspace,omitempty,omitzero" yaml:"workspace,omitempty" mapstructure:"workspace,omitempty"`
}

type EventPayload map[string]interface{}

type EventResult string

const EventResultCancelled EventResult = "cancelled"
const EventResultFailure EventResult = "failure"
const EventResultSuccess EventResult = "success"
const EventResultTimeout EventResult = "timeout"

var enumValues_EventResult = []interface{}{
	"success",
	"failure",
	"cancelled",
	"timeout",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventResult) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EventResult {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EventResult, v)
	}
	*j = EventResult(v)
	return nil
}

type EventRole string

const EventRoleBagong EventRole = "bagong"
const EventRoleGareng EventRole = "gareng"
const EventRolePetruk EventRole = "petruk"
const EventRoleSemar EventRole = "semar"

var enumValues_EventRole = []interface{}{
	"semar",
	"gareng",
	"petruk",
	"bagong",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventRole) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EventRole {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EventRole, v)
	}
	*j = EventRole(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Event) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Event: required")
	}
	if _, ok := raw["operation"]; raw != nil && !ok {
		return fmt.Errorf("field operation in Event: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in Event: required")
	}
	if _, ok := raw["run_id"]; raw != nil && !ok {
		return fmt.Errorf("field run_id in Event: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in Event: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Event: required")
	}
	type Plain Event
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.DurationMs != nil && 0 > *plain.DurationMs {
		return fmt.Errorf("field %s: must be >= %v", "duration_ms", 0)
	}
	*j = Event(plain)
	return nil
}

// A single piece of evidence linked to a task run and its supporting artifact. See
// punakawan-go-typescript-detailed-plan.md §17.
type EvidenceRecord struct {
	// ContentHash corresponds to the JSON schema field "content_hash".
	ContentHash *string `json:"content_hash,omitempty,omitzero" yaml:"content_hash,omitempty" mapstructure:"content_hash,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero" yaml:"path,omitempty" mapstructure:"path,omitempty"`

	// RunId corresponds to the JSON schema field "run_id".
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`

	// TaskId corresponds to the JSON schema field "task_id".
	TaskId *string `json:"task_id,omitempty,omitzero" yaml:"task_id,omitempty" mapstructure:"task_id,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type EvidenceRecordType `json:"type" yaml:"type" mapstructure:"type"`
}

type EvidenceRecordType string

const EvidenceRecordTypeApiDiff EvidenceRecordType = "api-diff"
const EvidenceRecordTypeApprovalRecord EvidenceRecordType = "approval-record"
const EvidenceRecordTypeCommandOutput EvidenceRecordType = "command-output"
const EvidenceRecordTypeCommit EvidenceRecordType = "commit"
const EvidenceRecordTypeExternalResponse EvidenceRecordType = "external-response"
const EvidenceRecordTypeGitDiff EvidenceRecordType = "git-diff"
const EvidenceRecordTypePlaywrightTrace EvidenceRecordType = "playwright-trace"
const EvidenceRecordTypeRepositorySnapshot EvidenceRecordType = "repository-snapshot"
const EvidenceRecordTypeReviewFinding EvidenceRecordType = "review-finding"
const EvidenceRecordTypeScreenshot EvidenceRecordType = "screenshot"
const EvidenceRecordTypeSourceExcerpt EvidenceRecordType = "source-excerpt"
const EvidenceRecordTypeTestReport EvidenceRecordType = "test-report"
const EvidenceRecordTypeUserAnswer EvidenceRecordType = "user-answer"

var enumValues_EvidenceRecordType = []interface{}{
	"source-excerpt",
	"repository-snapshot",
	"command-output",
	"test-report",
	"playwright-trace",
	"screenshot",
	"api-diff",
	"git-diff",
	"commit",
	"user-answer",
	"approval-record",
	"external-response",
	"review-finding",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceRecordType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EvidenceRecordType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EvidenceRecordType, v)
	}
	*j = EvidenceRecordType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceRecord) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in EvidenceRecord: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in EvidenceRecord: required")
	}
	if _, ok := raw["run_id"]; raw != nil && !ok {
		return fmt.Errorf("field run_id in EvidenceRecord: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in EvidenceRecord: required")
	}
	type Plain EvidenceRecord
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ContentHash != nil {
		if matched, _ := regexp.MatchString(`^sha256:[0-9a-f]{64}$`, string(*plain.ContentHash)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "ContentHash", `^sha256:[0-9a-f]{64}$`)
		}
	}
	*j = EvidenceRecord(plain)
	return nil
}

// A durable knowledge record with provenance and validity state. See
// punakawan-go-typescript-detailed-plan.md §7.
type KnowledgeRecord struct {
	// Bagong's independent final review, present on bagong-review records. See §8.4.
	BagongReview *KnowledgeRecordBagongReview `json:"bagong_review,omitempty,omitzero" yaml:"bagong_review,omitempty" mapstructure:"bagong_review,omitempty"`

	// Semar's pre-planning context dossier, present on context-dossier records. See
	// §9.1.
	ContextDossier *KnowledgeRecordContextDossier `json:"context_dossier,omitempty,omitzero" yaml:"context_dossier,omitempty" mapstructure:"context_dossier,omitempty"`

	// Extraction corresponds to the JSON schema field "extraction".
	Extraction KnowledgeRecordExtraction `json:"extraction" yaml:"extraction" mapstructure:"extraction"`

	// Semar's final implementation plan, present on final-plan records. See §9.3.
	FinalPlan *KnowledgeRecordFinalPlan `json:"final_plan,omitempty,omitzero" yaml:"final_plan,omitempty" mapstructure:"final_plan,omitempty"`

	// Formatting conventions, present on convention-profile records. See §27.3.
	Formatting *KnowledgeRecordFormatting `json:"formatting,omitempty,omitzero" yaml:"formatting,omitempty" mapstructure:"formatting,omitempty"`

	// Gareng's feasibility and risk review, present on gareng-review records. See
	// §8.2.
	GarengReview *KnowledgeRecordGarengReview `json:"gareng_review,omitempty,omitzero" yaml:"gareng_review,omitempty" mapstructure:"gareng_review,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Petruk's usefulness challenge and implementation planning output, present on
	// petruk-plan records. See §8.3.
	PetrukPlan *KnowledgeRecordPetrukPlan `json:"petruk_plan,omitempty,omitzero" yaml:"petruk_plan,omitempty" mapstructure:"petruk_plan,omitempty"`

	// Relations corresponds to the JSON schema field "relations".
	Relations []KnowledgeRecordRelationsElem `json:"relations,omitempty,omitzero" yaml:"relations,omitempty" mapstructure:"relations,omitempty"`

	// Semar's consolidated output after merging Gareng and Petruk findings, present
	// on semar-synthesis records. See §8.1, §9.2.
	SemarSynthesis *KnowledgeRecordSemarSynthesis `json:"semar_synthesis,omitempty,omitzero" yaml:"semar_synthesis,omitempty" mapstructure:"semar_synthesis,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source KnowledgeRecordSource `json:"source" yaml:"source" mapstructure:"source"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status" yaml:"status" mapstructure:"status"`

	// Structural conventions, present on convention-profile records. See §27.3.
	Structure *KnowledgeRecordStructure `json:"structure,omitempty,omitzero" yaml:"structure,omitempty" mapstructure:"structure,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Type corresponds to the JSON schema field "type".
	Type KnowledgeRecordType `json:"type" yaml:"type" mapstructure:"type"`

	// Validity corresponds to the JSON schema field "validity".
	Validity KnowledgeRecordValidity `json:"validity" yaml:"validity" mapstructure:"validity"`
}

// Bagong's independent final review, present on bagong-review records. See §8.4.
type KnowledgeRecordBagongReview struct {
	// BlockingFindings corresponds to the JSON schema field "blocking_findings".
	BlockingFindings []string `json:"blocking_findings,omitempty,omitzero" yaml:"blocking_findings,omitempty" mapstructure:"blocking_findings,omitempty"`

	// CompatibilityFindings corresponds to the JSON schema field
	// "compatibility_findings".
	CompatibilityFindings []string `json:"compatibility_findings,omitempty,omitzero" yaml:"compatibility_findings,omitempty" mapstructure:"compatibility_findings,omitempty"`

	// Findings corresponds to the JSON schema field "findings".
	Findings []string `json:"findings,omitempty,omitzero" yaml:"findings,omitempty" mapstructure:"findings,omitempty"`

	// HonestSummary corresponds to the JSON schema field "honest_summary".
	HonestSummary *string `json:"honest_summary,omitempty,omitzero" yaml:"honest_summary,omitempty" mapstructure:"honest_summary,omitempty"`

	// RequirementCoverage corresponds to the JSON schema field
	// "requirement_coverage".
	RequirementCoverage []string `json:"requirement_coverage,omitempty,omitzero" yaml:"requirement_coverage,omitempty" mapstructure:"requirement_coverage,omitempty"`

	// SecurityFindings corresponds to the JSON schema field "security_findings".
	SecurityFindings []string `json:"security_findings,omitempty,omitzero" yaml:"security_findings,omitempty" mapstructure:"security_findings,omitempty"`

	// TestGaps corresponds to the JSON schema field "test_gaps".
	TestGaps []string `json:"test_gaps,omitempty,omitzero" yaml:"test_gaps,omitempty" mapstructure:"test_gaps,omitempty"`

	// Uncertainties corresponds to the JSON schema field "uncertainties".
	Uncertainties []string `json:"uncertainties,omitempty,omitzero" yaml:"uncertainties,omitempty" mapstructure:"uncertainties,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict *string `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

// Semar's pre-planning context dossier, present on context-dossier records. See
// §9.1.
type KnowledgeRecordContextDossier struct {
	// AffectedRepositories corresponds to the JSON schema field
	// "affected_repositories".
	AffectedRepositories []string `json:"affected_repositories,omitempty,omitzero" yaml:"affected_repositories,omitempty" mapstructure:"affected_repositories,omitempty"`

	// ApiAndDataContracts corresponds to the JSON schema field
	// "api_and_data_contracts".
	ApiAndDataContracts []string `json:"api_and_data_contracts,omitempty,omitzero" yaml:"api_and_data_contracts,omitempty" mapstructure:"api_and_data_contracts,omitempty"`

	// Assumptions corresponds to the JSON schema field "assumptions".
	Assumptions []string `json:"assumptions,omitempty,omitzero" yaml:"assumptions,omitempty" mapstructure:"assumptions,omitempty"`

	// BusinessOrUserValue corresponds to the JSON schema field
	// "business_or_user_value".
	BusinessOrUserValue *string `json:"business_or_user_value,omitempty,omitzero" yaml:"business_or_user_value,omitempty" mapstructure:"business_or_user_value,omitempty"`

	// ConfidenceLevel corresponds to the JSON schema field "confidence_level".
	ConfidenceLevel *string `json:"confidence_level,omitempty,omitzero" yaml:"confidence_level,omitempty" mapstructure:"confidence_level,omitempty"`

	// Contradictions corresponds to the JSON schema field "contradictions".
	Contradictions []string `json:"contradictions,omitempty,omitzero" yaml:"contradictions,omitempty" mapstructure:"contradictions,omitempty"`

	// CurrentBehavior corresponds to the JSON schema field "current_behavior".
	CurrentBehavior *string `json:"current_behavior,omitempty,omitzero" yaml:"current_behavior,omitempty" mapstructure:"current_behavior,omitempty"`

	// DeploymentPath corresponds to the JSON schema field "deployment_path".
	DeploymentPath *string `json:"deployment_path,omitempty,omitzero" yaml:"deployment_path,omitempty" mapstructure:"deployment_path,omitempty"`

	// DesiredBehavior corresponds to the JSON schema field "desired_behavior".
	DesiredBehavior *string `json:"desired_behavior,omitempty,omitzero" yaml:"desired_behavior,omitempty" mapstructure:"desired_behavior,omitempty"`

	// ExistingImplementationPaths corresponds to the JSON schema field
	// "existing_implementation_paths".
	ExistingImplementationPaths []string `json:"existing_implementation_paths,omitempty,omitzero" yaml:"existing_implementation_paths,omitempty" mapstructure:"existing_implementation_paths,omitempty"`

	// ExistingTests corresponds to the JSON schema field "existing_tests".
	ExistingTests []string `json:"existing_tests,omitempty,omitzero" yaml:"existing_tests,omitempty" mapstructure:"existing_tests,omitempty"`

	// ExplicitNonGoals corresponds to the JSON schema field "explicit_non_goals".
	ExplicitNonGoals []string `json:"explicit_non_goals,omitempty,omitzero" yaml:"explicit_non_goals,omitempty" mapstructure:"explicit_non_goals,omitempty"`

	// MissingInformation corresponds to the JSON schema field "missing_information".
	MissingInformation []string `json:"missing_information,omitempty,omitzero" yaml:"missing_information,omitempty" mapstructure:"missing_information,omitempty"`

	// RelevantPreviousDecisions corresponds to the JSON schema field
	// "relevant_previous_decisions".
	RelevantPreviousDecisions []string `json:"relevant_previous_decisions,omitempty,omitzero" yaml:"relevant_previous_decisions,omitempty" mapstructure:"relevant_previous_decisions,omitempty"`

	// SourceInventory corresponds to the JSON schema field "source_inventory".
	SourceInventory []string `json:"source_inventory,omitempty,omitzero" yaml:"source_inventory,omitempty" mapstructure:"source_inventory,omitempty"`

	// UserGoal corresponds to the JSON schema field "user_goal".
	UserGoal *string `json:"user_goal,omitempty,omitzero" yaml:"user_goal,omitempty" mapstructure:"user_goal,omitempty"`
}

type KnowledgeRecordExtraction struct {
	// Confidence corresponds to the JSON schema field "confidence".
	Confidence *float64 `json:"confidence,omitempty,omitzero" yaml:"confidence,omitempty" mapstructure:"confidence,omitempty"`

	// ExtractorVersion corresponds to the JSON schema field "extractor_version".
	ExtractorVersion *string `json:"extractor_version,omitempty,omitzero" yaml:"extractor_version,omitempty" mapstructure:"extractor_version,omitempty"`

	// Method corresponds to the JSON schema field "method".
	Method KnowledgeRecordExtractionMethod `json:"method" yaml:"method" mapstructure:"method"`
}

type KnowledgeRecordExtractionMethod string

const KnowledgeRecordExtractionMethodImported KnowledgeRecordExtractionMethod = "imported"
const KnowledgeRecordExtractionMethodManual KnowledgeRecordExtractionMethod = "manual"
const KnowledgeRecordExtractionMethodModelAssisted KnowledgeRecordExtractionMethod = "model-assisted"

var enumValues_KnowledgeRecordExtractionMethod = []interface{}{
	"model-assisted",
	"manual",
	"imported",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordExtractionMethod) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KnowledgeRecordExtractionMethod {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KnowledgeRecordExtractionMethod, v)
	}
	*j = KnowledgeRecordExtractionMethod(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordExtraction) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in KnowledgeRecordExtraction: required")
	}
	type Plain KnowledgeRecordExtraction
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Confidence != nil && 1 < *plain.Confidence {
		return fmt.Errorf("field %s: must be <= %v", "confidence", 1)
	}
	if plain.Confidence != nil && 0 > *plain.Confidence {
		return fmt.Errorf("field %s: must be >= %v", "confidence", 0)
	}
	*j = KnowledgeRecordExtraction(plain)
	return nil
}

// Semar's final implementation plan, present on final-plan records. See §9.3.
type KnowledgeRecordFinalPlan struct {
	// AcceptanceCriteria corresponds to the JSON schema field "acceptance_criteria".
	AcceptanceCriteria []string `json:"acceptance_criteria,omitempty,omitzero" yaml:"acceptance_criteria,omitempty" mapstructure:"acceptance_criteria,omitempty"`

	// ApiImpact corresponds to the JSON schema field "api_impact".
	ApiImpact *string `json:"api_impact,omitempty,omitzero" yaml:"api_impact,omitempty" mapstructure:"api_impact,omitempty"`

	// ArchitectureDecision corresponds to the JSON schema field
	// "architecture_decision".
	ArchitectureDecision *string `json:"architecture_decision,omitempty,omitzero" yaml:"architecture_decision,omitempty" mapstructure:"architecture_decision,omitempty"`

	// CompatibilityConsiderations corresponds to the JSON schema field
	// "compatibility_considerations".
	CompatibilityConsiderations []string `json:"compatibility_considerations,omitempty,omitzero" yaml:"compatibility_considerations,omitempty" mapstructure:"compatibility_considerations,omitempty"`

	// DataModelImpact corresponds to the JSON schema field "data_model_impact".
	DataModelImpact *string `json:"data_model_impact,omitempty,omitzero" yaml:"data_model_impact,omitempty" mapstructure:"data_model_impact,omitempty"`

	// DeploymentChanges corresponds to the JSON schema field "deployment_changes".
	DeploymentChanges []string `json:"deployment_changes,omitempty,omitzero" yaml:"deployment_changes,omitempty" mapstructure:"deployment_changes,omitempty"`

	// DocumentationPlan corresponds to the JSON schema field "documentation_plan".
	DocumentationPlan []string `json:"documentation_plan,omitempty,omitzero" yaml:"documentation_plan,omitempty" mapstructure:"documentation_plan,omitempty"`

	// E2EPlan corresponds to the JSON schema field "e2e_plan".
	E2EPlan []string `json:"e2e_plan,omitempty,omitzero" yaml:"e2e_plan,omitempty" mapstructure:"e2e_plan,omitempty"`

	// ImplementationSequence corresponds to the JSON schema field
	// "implementation_sequence".
	ImplementationSequence []string `json:"implementation_sequence,omitempty,omitzero" yaml:"implementation_sequence,omitempty" mapstructure:"implementation_sequence,omitempty"`

	// IntegrationTestPlan corresponds to the JSON schema field
	// "integration_test_plan".
	IntegrationTestPlan []string `json:"integration_test_plan,omitempty,omitzero" yaml:"integration_test_plan,omitempty" mapstructure:"integration_test_plan,omitempty"`

	// MigrationPlan corresponds to the JSON schema field "migration_plan".
	MigrationPlan []string `json:"migration_plan,omitempty,omitzero" yaml:"migration_plan,omitempty" mapstructure:"migration_plan,omitempty"`

	// NonGoals corresponds to the JSON schema field "non_goals".
	NonGoals []string `json:"non_goals,omitempty,omitzero" yaml:"non_goals,omitempty" mapstructure:"non_goals,omitempty"`

	// ObservabilityPlan corresponds to the JSON schema field "observability_plan".
	ObservabilityPlan []string `json:"observability_plan,omitempty,omitzero" yaml:"observability_plan,omitempty" mapstructure:"observability_plan,omitempty"`

	// RepositoryImpactMap corresponds to the JSON schema field
	// "repository_impact_map".
	RepositoryImpactMap KnowledgeRecordFinalPlanRepositoryImpactMap `json:"repository_impact_map,omitempty,omitzero" yaml:"repository_impact_map,omitempty" mapstructure:"repository_impact_map,omitempty"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements []string `json:"requirements,omitempty,omitzero" yaml:"requirements,omitempty" mapstructure:"requirements,omitempty"`

	// RisksAndMitigations corresponds to the JSON schema field
	// "risks_and_mitigations".
	RisksAndMitigations []string `json:"risks_and_mitigations,omitempty,omitzero" yaml:"risks_and_mitigations,omitempty" mapstructure:"risks_and_mitigations,omitempty"`

	// RollbackPlan corresponds to the JSON schema field "rollback_plan".
	RollbackPlan []string `json:"rollback_plan,omitempty,omitzero" yaml:"rollback_plan,omitempty" mapstructure:"rollback_plan,omitempty"`

	// SecurityConsiderations corresponds to the JSON schema field
	// "security_considerations".
	SecurityConsiderations []string `json:"security_considerations,omitempty,omitzero" yaml:"security_considerations,omitempty" mapstructure:"security_considerations,omitempty"`

	// UnitTestPlan corresponds to the JSON schema field "unit_test_plan".
	UnitTestPlan []string `json:"unit_test_plan,omitempty,omitzero" yaml:"unit_test_plan,omitempty" mapstructure:"unit_test_plan,omitempty"`

	// VerificationCriteria corresponds to the JSON schema field
	// "verification_criteria".
	VerificationCriteria []string `json:"verification_criteria,omitempty,omitzero" yaml:"verification_criteria,omitempty" mapstructure:"verification_criteria,omitempty"`
}

type KnowledgeRecordFinalPlanRepositoryImpactMap map[string]string

// Formatting conventions, present on convention-profile records. See §27.3.
type KnowledgeRecordFormatting struct {
	// Editorconfig corresponds to the JSON schema field "editorconfig".
	Editorconfig *bool `json:"editorconfig,omitempty,omitzero" yaml:"editorconfig,omitempty" mapstructure:"editorconfig,omitempty"`

	// Formatters corresponds to the JSON schema field "formatters".
	Formatters []string `json:"formatters,omitempty,omitzero" yaml:"formatters,omitempty" mapstructure:"formatters,omitempty"`

	// Linters corresponds to the JSON schema field "linters".
	Linters []string `json:"linters,omitempty,omitzero" yaml:"linters,omitempty" mapstructure:"linters,omitempty"`
}

// Gareng's feasibility and risk review, present on gareng-review records. See
// §8.2.
type KnowledgeRecordGarengReview struct {
	// BlockingFindings corresponds to the JSON schema field "blocking_findings".
	BlockingFindings []string `json:"blocking_findings,omitempty,omitzero" yaml:"blocking_findings,omitempty" mapstructure:"blocking_findings,omitempty"`

	// MissingAcceptanceCriteria corresponds to the JSON schema field
	// "missing_acceptance_criteria".
	MissingAcceptanceCriteria []string `json:"missing_acceptance_criteria,omitempty,omitzero" yaml:"missing_acceptance_criteria,omitempty" mapstructure:"missing_acceptance_criteria,omitempty"`

	// NonBlockingFindings corresponds to the JSON schema field
	// "non_blocking_findings".
	NonBlockingFindings []string `json:"non_blocking_findings,omitempty,omitzero" yaml:"non_blocking_findings,omitempty" mapstructure:"non_blocking_findings,omitempty"`

	// RecommendedDefaults corresponds to the JSON schema field
	// "recommended_defaults".
	RecommendedDefaults []string `json:"recommended_defaults,omitempty,omitzero" yaml:"recommended_defaults,omitempty" mapstructure:"recommended_defaults,omitempty"`

	// RequiredEvidence corresponds to the JSON schema field "required_evidence".
	RequiredEvidence []string `json:"required_evidence,omitempty,omitzero" yaml:"required_evidence,omitempty" mapstructure:"required_evidence,omitempty"`

	// Risks corresponds to the JSON schema field "risks".
	Risks []string `json:"risks,omitempty,omitzero" yaml:"risks,omitempty" mapstructure:"risks,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict *string `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

// Petruk's usefulness challenge and implementation planning output, present on
// petruk-plan records. See §8.3.
type KnowledgeRecordPetrukPlan struct {
	// Alternatives corresponds to the JSON schema field "alternatives".
	Alternatives []string `json:"alternatives,omitempty,omitzero" yaml:"alternatives,omitempty" mapstructure:"alternatives,omitempty"`

	// DeploymentPlan corresponds to the JSON schema field "deployment_plan".
	DeploymentPlan []string `json:"deployment_plan,omitempty,omitzero" yaml:"deployment_plan,omitempty" mapstructure:"deployment_plan,omitempty"`

	// DocumentationPlan corresponds to the JSON schema field "documentation_plan".
	DocumentationPlan []string `json:"documentation_plan,omitempty,omitzero" yaml:"documentation_plan,omitempty" mapstructure:"documentation_plan,omitempty"`

	// E2EPlan corresponds to the JSON schema field "e2e_plan".
	E2EPlan []string `json:"e2e_plan,omitempty,omitzero" yaml:"e2e_plan,omitempty" mapstructure:"e2e_plan,omitempty"`

	// ImplementationSteps corresponds to the JSON schema field
	// "implementation_steps".
	ImplementationSteps []string `json:"implementation_steps,omitempty,omitzero" yaml:"implementation_steps,omitempty" mapstructure:"implementation_steps,omitempty"`

	// RecommendedSolution corresponds to the JSON schema field
	// "recommended_solution".
	RecommendedSolution *string `json:"recommended_solution,omitempty,omitzero" yaml:"recommended_solution,omitempty" mapstructure:"recommended_solution,omitempty"`

	// RepositoryChanges corresponds to the JSON schema field "repository_changes".
	RepositoryChanges []string `json:"repository_changes,omitempty,omitzero" yaml:"repository_changes,omitempty" mapstructure:"repository_changes,omitempty"`

	// TestPlan corresponds to the JSON schema field "test_plan".
	TestPlan []string `json:"test_plan,omitempty,omitzero" yaml:"test_plan,omitempty" mapstructure:"test_plan,omitempty"`

	// Tradeoffs corresponds to the JSON schema field "tradeoffs".
	Tradeoffs []string `json:"tradeoffs,omitempty,omitzero" yaml:"tradeoffs,omitempty" mapstructure:"tradeoffs,omitempty"`
}

type KnowledgeRecordRelationsElem struct {
	// Target corresponds to the JSON schema field "target".
	Target string `json:"target" yaml:"target" mapstructure:"target"`

	// Type corresponds to the JSON schema field "type".
	Type KnowledgeRecordRelationsElemType `json:"type" yaml:"type" mapstructure:"type"`
}

type KnowledgeRecordRelationsElemType string

const KnowledgeRecordRelationsElemTypeAppliesTo KnowledgeRecordRelationsElemType = "applies-to"
const KnowledgeRecordRelationsElemTypeAssumes KnowledgeRecordRelationsElemType = "assumes"
const KnowledgeRecordRelationsElemTypeAutomatedBy KnowledgeRecordRelationsElemType = "automated-by"
const KnowledgeRecordRelationsElemTypeBlocks KnowledgeRecordRelationsElemType = "blocks"
const KnowledgeRecordRelationsElemTypeConflictsWith KnowledgeRecordRelationsElemType = "conflicts-with"
const KnowledgeRecordRelationsElemTypeDependsOn KnowledgeRecordRelationsElemType = "depends-on"
const KnowledgeRecordRelationsElemTypeDeployedBy KnowledgeRecordRelationsElemType = "deployed-by"
const KnowledgeRecordRelationsElemTypeDerivedFrom KnowledgeRecordRelationsElemType = "derived-from"
const KnowledgeRecordRelationsElemTypeDiscoveredFrom KnowledgeRecordRelationsElemType = "discovered-from"
const KnowledgeRecordRelationsElemTypeDocumentedIn KnowledgeRecordRelationsElemType = "documented-in"
const KnowledgeRecordRelationsElemTypeImplements KnowledgeRecordRelationsElemType = "implements"
const KnowledgeRecordRelationsElemTypeObservedIn KnowledgeRecordRelationsElemType = "observed-in"
const KnowledgeRecordRelationsElemTypeOwnedBy KnowledgeRecordRelationsElemType = "owned-by"
const KnowledgeRecordRelationsElemTypeRelatedTo KnowledgeRecordRelationsElemType = "related-to"
const KnowledgeRecordRelationsElemTypeResolves KnowledgeRecordRelationsElemType = "resolves"
const KnowledgeRecordRelationsElemTypeSupersedes KnowledgeRecordRelationsElemType = "supersedes"
const KnowledgeRecordRelationsElemTypeTestedBy KnowledgeRecordRelationsElemType = "tested-by"
const KnowledgeRecordRelationsElemTypeTrackedBy KnowledgeRecordRelationsElemType = "tracked-by"
const KnowledgeRecordRelationsElemTypeValidates KnowledgeRecordRelationsElemType = "validates"
const KnowledgeRecordRelationsElemTypeVerifiedBy KnowledgeRecordRelationsElemType = "verified-by"

var enumValues_KnowledgeRecordRelationsElemType = []interface{}{
	"derived-from",
	"supersedes",
	"implements",
	"validates",
	"tested-by",
	"automated-by",
	"deployed-by",
	"depends-on",
	"blocks",
	"related-to",
	"conflicts-with",
	"owned-by",
	"applies-to",
	"verified-by",
	"discovered-from",
	"documented-in",
	"tracked-by",
	"observed-in",
	"assumes",
	"resolves",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordRelationsElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KnowledgeRecordRelationsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KnowledgeRecordRelationsElemType, v)
	}
	*j = KnowledgeRecordRelationsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordRelationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["target"]; raw != nil && !ok {
		return fmt.Errorf("field target in KnowledgeRecordRelationsElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in KnowledgeRecordRelationsElem: required")
	}
	type Plain KnowledgeRecordRelationsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = KnowledgeRecordRelationsElem(plain)
	return nil
}

// Semar's consolidated output after merging Gareng and Petruk findings, present on
// semar-synthesis records. See §8.1, §9.2.
type KnowledgeRecordSemarSynthesis struct {
	// AffectedComponents corresponds to the JSON schema field "affected_components".
	AffectedComponents []string `json:"affected_components,omitempty,omitzero" yaml:"affected_components,omitempty" mapstructure:"affected_components,omitempty"`

	// AffectedRepositories corresponds to the JSON schema field
	// "affected_repositories".
	AffectedRepositories []string `json:"affected_repositories,omitempty,omitzero" yaml:"affected_repositories,omitempty" mapstructure:"affected_repositories,omitempty"`

	// Assumptions corresponds to the JSON schema field "assumptions".
	Assumptions []string `json:"assumptions,omitempty,omitzero" yaml:"assumptions,omitempty" mapstructure:"assumptions,omitempty"`

	// Goal corresponds to the JSON schema field "goal".
	Goal *string `json:"goal,omitempty,omitzero" yaml:"goal,omitempty" mapstructure:"goal,omitempty"`

	// KnownFacts corresponds to the JSON schema field "known_facts".
	KnownFacts []string `json:"known_facts,omitempty,omitzero" yaml:"known_facts,omitempty" mapstructure:"known_facts,omitempty"`

	// NextGate corresponds to the JSON schema field "next_gate".
	NextGate *string `json:"next_gate,omitempty,omitzero" yaml:"next_gate,omitempty" mapstructure:"next_gate,omitempty"`

	// OpenQuestions corresponds to the JSON schema field "open_questions".
	OpenQuestions []KnowledgeRecordSemarSynthesisOpenQuestionsElem `json:"open_questions,omitempty,omitzero" yaml:"open_questions,omitempty" mapstructure:"open_questions,omitempty"`

	// RecommendedWorkflow corresponds to the JSON schema field
	// "recommended_workflow".
	RecommendedWorkflow *string `json:"recommended_workflow,omitempty,omitzero" yaml:"recommended_workflow,omitempty" mapstructure:"recommended_workflow,omitempty"`

	// Risks corresponds to the JSON schema field "risks".
	Risks []string `json:"risks,omitempty,omitzero" yaml:"risks,omitempty" mapstructure:"risks,omitempty"`

	// Scope corresponds to the JSON schema field "scope".
	Scope *string `json:"scope,omitempty,omitzero" yaml:"scope,omitempty" mapstructure:"scope,omitempty"`
}

type KnowledgeRecordSemarSynthesisOpenQuestionsElem struct {
	// Blocking corresponds to the JSON schema field "blocking".
	Blocking *bool `json:"blocking,omitempty,omitzero" yaml:"blocking,omitempty" mapstructure:"blocking,omitempty"`

	// ImpactIfUnanswered corresponds to the JSON schema field "impact_if_unanswered".
	ImpactIfUnanswered *string `json:"impact_if_unanswered,omitempty,omitzero" yaml:"impact_if_unanswered,omitempty" mapstructure:"impact_if_unanswered,omitempty"`

	// ObservedConflict corresponds to the JSON schema field "observed_conflict".
	ObservedConflict *string `json:"observed_conflict,omitempty,omitzero" yaml:"observed_conflict,omitempty" mapstructure:"observed_conflict,omitempty"`

	// Question corresponds to the JSON schema field "question".
	Question *string `json:"question,omitempty,omitzero" yaml:"question,omitempty" mapstructure:"question,omitempty"`

	// RecommendedDefault corresponds to the JSON schema field "recommended_default".
	RecommendedDefault *string `json:"recommended_default,omitempty,omitzero" yaml:"recommended_default,omitempty" mapstructure:"recommended_default,omitempty"`

	// Target corresponds to the JSON schema field "target".
	Target *KnowledgeRecordSemarSynthesisOpenQuestionsElemTarget `json:"target,omitempty,omitzero" yaml:"target,omitempty" mapstructure:"target,omitempty"`

	// WhyItMatters corresponds to the JSON schema field "why_it_matters".
	WhyItMatters *string `json:"why_it_matters,omitempty,omitzero" yaml:"why_it_matters,omitempty" mapstructure:"why_it_matters,omitempty"`
}

type KnowledgeRecordSemarSynthesisOpenQuestionsElemTarget struct {
	// Reference corresponds to the JSON schema field "reference".
	Reference *string `json:"reference,omitempty,omitzero" yaml:"reference,omitempty" mapstructure:"reference,omitempty"`

	// System corresponds to the JSON schema field "system".
	System *string `json:"system,omitempty,omitzero" yaml:"system,omitempty" mapstructure:"system,omitempty"`
}

type KnowledgeRecordSource struct {
	// ContentHash corresponds to the JSON schema field "content_hash".
	ContentHash *string `json:"content_hash,omitempty,omitzero" yaml:"content_hash,omitempty" mapstructure:"content_hash,omitempty"`

	// ExternalId corresponds to the JSON schema field "external_id".
	ExternalId *string `json:"external_id,omitempty,omitzero" yaml:"external_id,omitempty" mapstructure:"external_id,omitempty"`

	// Provider corresponds to the JSON schema field "provider".
	Provider string `json:"provider" yaml:"provider" mapstructure:"provider"`

	// RetrievedAt corresponds to the JSON schema field "retrieved_at".
	RetrievedAt time.Time `json:"retrieved_at" yaml:"retrieved_at" mapstructure:"retrieved_at"`

	// Section corresponds to the JSON schema field "section".
	Section *string `json:"section,omitempty,omitzero" yaml:"section,omitempty" mapstructure:"section,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri *string `json:"uri,omitempty,omitzero" yaml:"uri,omitempty" mapstructure:"uri,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version interface{} `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordSource) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["provider"]; raw != nil && !ok {
		return fmt.Errorf("field provider in KnowledgeRecordSource: required")
	}
	if _, ok := raw["retrieved_at"]; raw != nil && !ok {
		return fmt.Errorf("field retrieved_at in KnowledgeRecordSource: required")
	}
	type Plain KnowledgeRecordSource
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ContentHash != nil {
		if matched, _ := regexp.MatchString(`^sha256:[0-9a-f]{64}$`, string(*plain.ContentHash)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "ContentHash", `^sha256:[0-9a-f]{64}$`)
		}
	}
	*j = KnowledgeRecordSource(plain)
	return nil
}

// Structural conventions, present on convention-profile records. See §27.3.
type KnowledgeRecordStructure struct {
	// Layout corresponds to the JSON schema field "layout".
	Layout *string `json:"layout,omitempty,omitzero" yaml:"layout,omitempty" mapstructure:"layout,omitempty"`

	// NamingConvention corresponds to the JSON schema field "naming_convention".
	NamingConvention *string `json:"naming_convention,omitempty,omitzero" yaml:"naming_convention,omitempty" mapstructure:"naming_convention,omitempty"`

	// PackageManager corresponds to the JSON schema field "package_manager".
	PackageManager *string `json:"package_manager,omitempty,omitzero" yaml:"package_manager,omitempty" mapstructure:"package_manager,omitempty"`

	// TestFramework corresponds to the JSON schema field "test_framework".
	TestFramework []string `json:"test_framework,omitempty,omitzero" yaml:"test_framework,omitempty" mapstructure:"test_framework,omitempty"`
}

type KnowledgeRecordType string

const KnowledgeRecordTypeAcceptanceCriterion KnowledgeRecordType = "acceptance-criterion"
const KnowledgeRecordTypeAnswer KnowledgeRecordType = "answer"
const KnowledgeRecordTypeApiContract KnowledgeRecordType = "api-contract"
const KnowledgeRecordTypeAssumption KnowledgeRecordType = "assumption"
const KnowledgeRecordTypeBagongReview KnowledgeRecordType = "bagong-review"
const KnowledgeRecordTypeBrowserFlow KnowledgeRecordType = "browser-flow"
const KnowledgeRecordTypeChangeSet KnowledgeRecordType = "change-set"
const KnowledgeRecordTypeClaim KnowledgeRecordType = "claim"
const KnowledgeRecordTypeComponent KnowledgeRecordType = "component"
const KnowledgeRecordTypeConstraint KnowledgeRecordType = "constraint"
const KnowledgeRecordTypeContextDossier KnowledgeRecordType = "context-dossier"
const KnowledgeRecordTypeConventionProfile KnowledgeRecordType = "convention-profile"
const KnowledgeRecordTypeDataContract KnowledgeRecordType = "data-contract"
const KnowledgeRecordTypeDecision KnowledgeRecordType = "decision"
const KnowledgeRecordTypeDeploymentUnit KnowledgeRecordType = "deployment-unit"
const KnowledgeRecordTypeEvidence KnowledgeRecordType = "evidence"
const KnowledgeRecordTypeExternalReference KnowledgeRecordType = "external-reference"
const KnowledgeRecordTypeFinalPlan KnowledgeRecordType = "final-plan"
const KnowledgeRecordTypeGarengReview KnowledgeRecordType = "gareng-review"
const KnowledgeRecordTypePersonOrTeam KnowledgeRecordType = "person-or-team"
const KnowledgeRecordTypePetrukPlan KnowledgeRecordType = "petruk-plan"
const KnowledgeRecordTypeQuestion KnowledgeRecordType = "question"
const KnowledgeRecordTypeRepository KnowledgeRecordType = "repository"
const KnowledgeRecordTypeRequirement KnowledgeRecordType = "requirement"
const KnowledgeRecordTypeReviewFinding KnowledgeRecordType = "review-finding"
const KnowledgeRecordTypeRisk KnowledgeRecordType = "risk"
const KnowledgeRecordTypeSemarSynthesis KnowledgeRecordType = "semar-synthesis"
const KnowledgeRecordTypeSourceArtifact KnowledgeRecordType = "source-artifact"
const KnowledgeRecordTypeTestCase KnowledgeRecordType = "test-case"
const KnowledgeRecordTypeWorkItem KnowledgeRecordType = "work-item"
const KnowledgeRecordTypeWorkspace KnowledgeRecordType = "workspace"

var enumValues_KnowledgeRecordType = []interface{}{
	"workspace",
	"repository",
	"component",
	"source-artifact",
	"requirement",
	"acceptance-criterion",
	"claim",
	"assumption",
	"constraint",
	"decision",
	"question",
	"answer",
	"api-contract",
	"data-contract",
	"browser-flow",
	"test-case",
	"deployment-unit",
	"work-item",
	"change-set",
	"evidence",
	"external-reference",
	"person-or-team",
	"risk",
	"review-finding",
	"convention-profile",
	"context-dossier",
	"semar-synthesis",
	"gareng-review",
	"petruk-plan",
	"bagong-review",
	"final-plan",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KnowledgeRecordType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KnowledgeRecordType, v)
	}
	*j = KnowledgeRecordType(v)
	return nil
}

type KnowledgeRecordValidity struct {
	// State corresponds to the JSON schema field "state".
	State KnowledgeRecordValidityState `json:"state" yaml:"state" mapstructure:"state"`

	// VerifiedAt corresponds to the JSON schema field "verified_at".
	VerifiedAt *time.Time `json:"verified_at,omitempty,omitzero" yaml:"verified_at,omitempty" mapstructure:"verified_at,omitempty"`

	// VerifiedBy corresponds to the JSON schema field "verified_by".
	VerifiedBy []string `json:"verified_by,omitempty,omitzero" yaml:"verified_by,omitempty" mapstructure:"verified_by,omitempty"`
}

type KnowledgeRecordValidityState string

const KnowledgeRecordValidityStateAssumed KnowledgeRecordValidityState = "assumed"
const KnowledgeRecordValidityStateDisputed KnowledgeRecordValidityState = "disputed"
const KnowledgeRecordValidityStateInferred KnowledgeRecordValidityState = "inferred"
const KnowledgeRecordValidityStateInvalid KnowledgeRecordValidityState = "invalid"
const KnowledgeRecordValidityStateObserved KnowledgeRecordValidityState = "observed"
const KnowledgeRecordValidityStateStale KnowledgeRecordValidityState = "stale"
const KnowledgeRecordValidityStateSuperseded KnowledgeRecordValidityState = "superseded"
const KnowledgeRecordValidityStateVerified KnowledgeRecordValidityState = "verified"

var enumValues_KnowledgeRecordValidityState = []interface{}{
	"observed",
	"inferred",
	"assumed",
	"verified",
	"disputed",
	"superseded",
	"invalid",
	"stale",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordValidityState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KnowledgeRecordValidityState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KnowledgeRecordValidityState, v)
	}
	*j = KnowledgeRecordValidityState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecordValidity) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in KnowledgeRecordValidity: required")
	}
	type Plain KnowledgeRecordValidity
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = KnowledgeRecordValidity(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KnowledgeRecord) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["extraction"]; raw != nil && !ok {
		return fmt.Errorf("field extraction in KnowledgeRecord: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in KnowledgeRecord: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in KnowledgeRecord: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in KnowledgeRecord: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in KnowledgeRecord: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in KnowledgeRecord: required")
	}
	if _, ok := raw["validity"]; raw != nil && !ok {
		return fmt.Errorf("field validity in KnowledgeRecord: required")
	}
	type Plain KnowledgeRecord
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^pkw:[a-z]+/[a-z0-9-]+/.+$`, string(plain.Id)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Id", `^pkw:[a-z]+/[a-z0-9-]+/.+$`)
	}
	*j = KnowledgeRecord(plain)
	return nil
}

// A dependency-aware Beads work item generated from an approved plan. See
// punakawan-go-typescript-detailed-plan.md §10.
type TaskContract struct {
	// AcceptanceCriteria corresponds to the JSON schema field "acceptance_criteria".
	AcceptanceCriteria []string `json:"acceptance_criteria" yaml:"acceptance_criteria" mapstructure:"acceptance_criteria"`

	// ApprovalRequired corresponds to the JSON schema field "approval_required".
	ApprovalRequired *bool `json:"approval_required,omitempty,omitzero" yaml:"approval_required,omitempty" mapstructure:"approval_required,omitempty"`

	// BeadsEpic corresponds to the JSON schema field "beads_epic".
	BeadsEpic *string `json:"beads_epic,omitempty,omitzero" yaml:"beads_epic,omitempty" mapstructure:"beads_epic,omitempty"`

	// DefinitionOfDone corresponds to the JSON schema field "definition_of_done".
	DefinitionOfDone string `json:"definition_of_done" yaml:"definition_of_done" mapstructure:"definition_of_done"`

	// Dependencies corresponds to the JSON schema field "dependencies".
	Dependencies []TaskContractDependenciesElem `json:"dependencies,omitempty,omitzero" yaml:"dependencies,omitempty" mapstructure:"dependencies,omitempty"`

	// DiscoveredFrom corresponds to the JSON schema field "discovered_from".
	DiscoveredFrom *string `json:"discovered_from,omitempty,omitzero" yaml:"discovered_from,omitempty" mapstructure:"discovered_from,omitempty"`

	// ExpectedFilesOrComponents corresponds to the JSON schema field
	// "expected_files_or_components".
	ExpectedFilesOrComponents []string `json:"expected_files_or_components,omitempty,omitzero" yaml:"expected_files_or_components,omitempty" mapstructure:"expected_files_or_components,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// JiraKey corresponds to the JSON schema field "jira_key".
	JiraKey *string `json:"jira_key,omitempty,omitzero" yaml:"jira_key,omitempty" mapstructure:"jira_key,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository" yaml:"repository" mapstructure:"repository"`

	// RequiredEvidence corresponds to the JSON schema field "required_evidence".
	RequiredEvidence []string `json:"required_evidence,omitempty,omitzero" yaml:"required_evidence,omitempty" mapstructure:"required_evidence,omitempty"`

	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId string `json:"requirement_id" yaml:"requirement_id" mapstructure:"requirement_id"`

	// RiskClassification corresponds to the JSON schema field "risk_classification".
	RiskClassification *TaskContractRiskClassification `json:"risk_classification,omitempty,omitzero" yaml:"risk_classification,omitempty" mapstructure:"risk_classification,omitempty"`

	// Scope corresponds to the JSON schema field "scope".
	Scope string `json:"scope" yaml:"scope" mapstructure:"scope"`

	// TestRequirements corresponds to the JSON schema field "test_requirements".
	TestRequirements []string `json:"test_requirements,omitempty,omitzero" yaml:"test_requirements,omitempty" mapstructure:"test_requirements,omitempty"`
}

type TaskContractDependenciesElem struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Type corresponds to the JSON schema field "type".
	Type TaskContractDependenciesElemType `json:"type" yaml:"type" mapstructure:"type"`
}

type TaskContractDependenciesElemType string

const TaskContractDependenciesElemTypeBlocks TaskContractDependenciesElemType = "blocks"
const TaskContractDependenciesElemTypeDiscoveredFrom TaskContractDependenciesElemType = "discovered-from"
const TaskContractDependenciesElemTypeRequires TaskContractDependenciesElemType = "requires"

var enumValues_TaskContractDependenciesElemType = []interface{}{
	"blocks",
	"discovered-from",
	"requires",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskContractDependenciesElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskContractDependenciesElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskContractDependenciesElemType, v)
	}
	*j = TaskContractDependenciesElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskContractDependenciesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskContractDependenciesElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in TaskContractDependenciesElem: required")
	}
	type Plain TaskContractDependenciesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TaskContractDependenciesElem(plain)
	return nil
}

type TaskContractRiskClassification string

const TaskContractRiskClassificationHigh TaskContractRiskClassification = "high"
const TaskContractRiskClassificationLow TaskContractRiskClassification = "low"
const TaskContractRiskClassificationMedium TaskContractRiskClassification = "medium"

var enumValues_TaskContractRiskClassification = []interface{}{
	"low",
	"medium",
	"high",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskContractRiskClassification) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskContractRiskClassification {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskContractRiskClassification, v)
	}
	*j = TaskContractRiskClassification(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskContract) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["acceptance_criteria"]; raw != nil && !ok {
		return fmt.Errorf("field acceptance_criteria in TaskContract: required")
	}
	if _, ok := raw["definition_of_done"]; raw != nil && !ok {
		return fmt.Errorf("field definition_of_done in TaskContract: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskContract: required")
	}
	if _, ok := raw["repository"]; raw != nil && !ok {
		return fmt.Errorf("field repository in TaskContract: required")
	}
	if _, ok := raw["requirement_id"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_id in TaskContract: required")
	}
	if _, ok := raw["scope"]; raw != nil && !ok {
		return fmt.Errorf("field scope in TaskContract: required")
	}
	type Plain TaskContract
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AcceptanceCriteria != nil && len(plain.AcceptanceCriteria) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "acceptance_criteria", 1)
	}
	*j = TaskContract(plain)
	return nil
}

// A running or completed workflow instance and its state-machine position. See
// punakawan-go-typescript-detailed-plan.md §9, §18.1.
type WorkflowRun struct {
	// Checkpoints corresponds to the JSON schema field "checkpoints".
	Checkpoints []WorkflowRunCheckpointsElem `json:"checkpoints,omitempty,omitzero" yaml:"checkpoints,omitempty" mapstructure:"checkpoints,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// State corresponds to the JSON schema field "state".
	State WorkflowRunState `json:"state" yaml:"state" mapstructure:"state"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt time.Time `json:"updated_at" yaml:"updated_at" mapstructure:"updated_at"`

	// WorkflowName corresponds to the JSON schema field "workflow_name".
	WorkflowName WorkflowRunWorkflowName `json:"workflow_name" yaml:"workflow_name" mapstructure:"workflow_name"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace string `json:"workspace" yaml:"workspace" mapstructure:"workspace"`
}

type WorkflowRunCheckpointsElem struct {
	// At corresponds to the JSON schema field "at".
	At time.Time `json:"at" yaml:"at" mapstructure:"at"`

	// Note corresponds to the JSON schema field "note".
	Note *string `json:"note,omitempty,omitzero" yaml:"note,omitempty" mapstructure:"note,omitempty"`

	// State corresponds to the JSON schema field "state".
	State string `json:"state" yaml:"state" mapstructure:"state"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkflowRunCheckpointsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in WorkflowRunCheckpointsElem: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in WorkflowRunCheckpointsElem: required")
	}
	type Plain WorkflowRunCheckpointsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorkflowRunCheckpointsElem(plain)
	return nil
}

type WorkflowRunState string

const WorkflowRunStateAwaitingApproval WorkflowRunState = "awaiting-approval"
const WorkflowRunStateAwaitingClarification WorkflowRunState = "awaiting-clarification"
const WorkflowRunStateBlocked WorkflowRunState = "blocked"
const WorkflowRunStateCancelled WorkflowRunState = "cancelled"
const WorkflowRunStateCompleted WorkflowRunState = "completed"
const WorkflowRunStateContextBuilding WorkflowRunState = "context-building"
const WorkflowRunStateCreated WorkflowRunState = "created"
const WorkflowRunStateExecuting WorkflowRunState = "executing"
const WorkflowRunStateFailed WorkflowRunState = "failed"
const WorkflowRunStatePlanning WorkflowRunState = "planning"
const WorkflowRunStateReviewing WorkflowRunState = "reviewing"

var enumValues_WorkflowRunState = []interface{}{
	"created",
	"context-building",
	"awaiting-clarification",
	"planning",
	"awaiting-approval",
	"executing",
	"reviewing",
	"blocked",
	"completed",
	"failed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkflowRunState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WorkflowRunState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WorkflowRunState, v)
	}
	*j = WorkflowRunState(v)
	return nil
}

type WorkflowRunWorkflowName string

const WorkflowRunWorkflowNameBrowserFlowCapture WorkflowRunWorkflowName = "browser-flow-capture"
const WorkflowRunWorkflowNameFeatureDelivery WorkflowRunWorkflowName = "feature-delivery"
const WorkflowRunWorkflowNameFinalReview WorkflowRunWorkflowName = "final-review"
const WorkflowRunWorkflowNameImplementationOnly WorkflowRunWorkflowName = "implementation-only"
const WorkflowRunWorkflowNameRequirementReview WorkflowRunWorkflowName = "requirement-review"

var enumValues_WorkflowRunWorkflowName = []interface{}{
	"feature-delivery",
	"requirement-review",
	"browser-flow-capture",
	"implementation-only",
	"final-review",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkflowRunWorkflowName) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WorkflowRunWorkflowName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WorkflowRunWorkflowName, v)
	}
	*j = WorkflowRunWorkflowName(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkflowRun) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in WorkflowRun: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in WorkflowRun: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in WorkflowRun: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in WorkflowRun: required")
	}
	if _, ok := raw["workflow_name"]; raw != nil && !ok {
		return fmt.Errorf("field workflow_name in WorkflowRun: required")
	}
	if _, ok := raw["workspace"]; raw != nil && !ok {
		return fmt.Errorf("field workspace in WorkflowRun: required")
	}
	type Plain WorkflowRun
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorkflowRun(plain)
	return nil
}
